[package]
name = "smacker"
version = "0.1.0"
authors = ["Daniel Di Marco <d.dimarco@gmx.de>"]
edition = "2021"
build = "build.rs"
exclude = [
        "src/c/libsmacker-code/.svn/*",
        "src/c/libsmacker-code/Xcode/*",
        "src/c/libsmacker-code/*.dev",
        "src/c/libsmacker-code/*.cbp",
        "*.smk",
]

[dependencies]
libc = "0.2"

[build-dependencies]
# gcc crate was renamed to cc
cc = "1.2"
