note "sc_image is the most basic class with\niscripting capabilities.\nEach higher level element has a link\nto the lower level one in the\ncorresponding .dat file." as N1

class sc_image <|-- sc_sprite
sc_image : image_id
sc_image : iscript_pos
sc_image : frameset
sc_image : waiting_ticks_left
sc_image : overlays
sc_image : underlays

class sc_sprite <|-- sc_flingy
sc_sprite : sprite_id
sc_sprite : health_bar
sc_sprite : selection_circle

class sc_flingy <|-- sc_unit
sc_flingy : flingy_id
sc_flingy : speed

class sc_unit
sc_unit : unit_id
